# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Martin Seest Christiansen
title: Experienced technologist (engineering/architecture)
email: mseest@gmail.com
website: https://github.com/mseest/resume

# Social links
twitter_username: mseest
github_username:  mseest
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: mseest
linkedin_username: seest
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Martin and I'm an experienced technical leader with a demonstrated history working in the public and private industry. Strong engineering professional skilled, with hands on experience, as both developer and architect. Visionary pragmatic problem solver preaching Public Cloud and API first.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# darkmode: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
